version: '3.7'

services:
  web:
    build: src
    platform: linux/amd64
    ports:
      - "8090:80"

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DoIRM
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d