version: '3'
services:
  geoserver:
    build:
      context: .
    ports:
      - "${PORT}:8080"
    environment:
      - GEOSERVER_ADMIN_USER=temp
      - GEOSERVER_ADMIN_PASSWORD=temp
      - RUN_UNPRIVILEGED=true
      - ROOT_WEBAPP_REDIRECT=true
      - POSTGRES_JNDI_ENABLED=true
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_DB=geoserver
      - POSTGRES_USERNAME=geoserver
      - POSTGRES_PASSWORD=geoserver
      - POSTGRES_JNDI_RESOURCE_NAME=jdbc/postgres
    healthcheck:
      test: chmod -R 777 /usr/local/tomcat/webapps/
      interval: 10s
      retries: 3
      timeout: 20s
  postgis:
    image: postgis/postgis:16-3.4-alpine@sha256:f785413fbe19835b9fd7db0ec3bcb215de2b4f87ffaaadd01e2e8f44d9cefbf1
    environment:
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    healthcheck:
      test: pg_isready -U geoserver -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
