version: "3.7"
services:
  web:
    build:
      context: ./app
    ports:
      - 7777:80
    links:
      - cce_mysql
  cce_mysql:
    build:
      context: ./db
    environment:
      MYSQL_DATABASE: "cce"
      MYSQL_USER: "cce"
      MYSQL_PASSWORD: "cce"
      MYSQL_ROOT_PASSWORD: "cce"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  bot:
    platform: linux/amd64
    ports:
      - "8888:3000"
    build:
      context: bot
    cap_add:
      - SYS_ADMIN