version: "3.9"

services:
  db:
    image: mariadb:10.9.3-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=your_root_password
    volumes:
      - ./deploy/db:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

  app:
    build:
      context: ./deploy/app
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "10002:3000"

networks:
  internal:
