services:
    nginx:
        image: nginx:alpine
        ports:
            - '10000:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - app

    app:
        build:
            context: app
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
    db:
        image: mariadb:10.6.4-focal
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: guest
            MYSQL_PASSWORD: guest
            MYSQL_DATABASE: user_db
        command:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
